EATSTEAK/rusaint

- Cargo.toml
- README.md
- src/application/course_grades/data.rs
- src/application/course_grades/mod.rs
- src/application/course_schedule.rs
- src/application/mod.rs
- src/application/student_information.rs
- src/lib.rs
- src/session/mod.rs
- src/webdynpro/application/client/mod.rs
- src/webdynpro/element/list_box/mod.rs
- src/webdynpro/element/mod.rs
- src/webdynpro/element/sap_table/cell/mod.rs
- src/webdynpro/element/sap_table/mod.rs
- src/webdynpro/error/mod.rs
- src/webdynpro/mod.rs
- tests/tests.rs
- tests/webdynpro/application.rs
- tests/webdynpro/element/button.rs
- tests/webdynpro/element/mod.rs
- tests/webdynpro/mod.rs
> [feat] 성적 조회 기능 구현

- src/webdynpro/element/mod.rs
- 엘리먼트를 정의할 때 사용하는 `define_element_base` 와 `define_element_interactable`에서 임의의 Attribute 를 각 엘리먼트와 LSData, LSData의 필드에 붙일 수 있도록 개선하였습니다.
> [feat] 엘리먼트 정의 매크로의 Attribute 인식

- src/application/course_grades/mod.rs
- src/webdynpro/element/action/button.rs
- src/webdynpro/element/action/link.rs
- src/webdynpro/element/action/mod.rs
- src/webdynpro/element/complex/sap_table/cell/header_cell.rs
- src/webdynpro/element/complex/sap_table/cell/hierarchical_cell.rs
- src/webdynpro/element/complex/sap_table/cell/matrix_cell.rs
- src/webdynpro/element/complex/sap_table/cell/normal_cell.rs
- src/webdynpro/element/complex/sap_table/cell/selection_cell.rs
- src/webdynpro/element/complex/sap_table/mod.rs
- src/webdynpro/element/complex/sap_table/property.rs
- src/webdynpro/element/graphic/image.rs
- src/webdynpro/element/layout/button_row.rs
- src/webdynpro/element/layout/mod.rs
- src/webdynpro/element/layout/popup_window.rs
- src/webdynpro/element/layout/scroll_container.rs
- src/webdynpro/element/layout/scrollbar.rs
- src/webdynpro/element/layout/tray.rs
- src/webdynpro/element/mod.rs
- src/webdynpro/element/property/mod.rs
- 일부 엘리먼트에 대해 String 대신 enum 타입을 적용
- 올바르지 않은 LSData를 가진 엘리먼트 수정
> [feat] 일부 엘리먼트에 enum 타입 적용

- src/application/course_grades/mod.rs
- src/webdynpro/element/complex/sap_table/cell/header_cell.rs
- src/webdynpro/element/complex/sap_table/cell/hierarchical_cell.rs
- src/webdynpro/element/complex/sap_table/cell/matrix_cell.rs
- src/webdynpro/element/complex/sap_table/cell/normal_cell.rs
- src/webdynpro/element/complex/sap_table/cell/selection_cell.rs
- src/webdynpro/element/mod.rs
- src/webdynpro/element/selection/combo_box.rs
- src/webdynpro/element/text/caption.rs
- 각 엘리먼트의 LSData를 Deref하여 LSData 필드들을 쉽게 접근할 수 있습니다.
> [feat] 엘리먼트에 LSData deref 적용

- src/application/mod.rs
- src/error/mod.rs
- src/lib.rs
- src/session/mod.rs
- src/webdynpro/application/mod.rs
- src/webdynpro/error/mod.rs
- src/webdynpro/event/mod.rs
- src/webdynpro/event/ucf_parameters.rs
- 누락된 메소드, 구조체에 대한 설명을 추가했습니다.
- 자명한 것이나 정확한 용도를 알 수 없는 것에 대해서는 `#[allow(missing_docs)]`를 추가하였습니다.
> [docs] 누락된 설명 추가

- Cargo.toml
> [release] 0.1.1

- src/application/course_grades/mod.rs
- src/application/course_grades/model.rs
- `CourseGrades`에 학위과정을 선택할 수 있도록 개선하였습니다.
> [feat] CourseGrades에 학위과정 선택 추가

- tests/application/course_grades.rs
> [fix] `CourseGrades` 테스트

- src/application/course_grades/mod.rs
- src/application/course_schedule.rs
- src/webdynpro/element/complex/sap_table/body.rs
- src/webdynpro/element/complex/sap_table/from_sap_table.rs
- src/webdynpro/element/complex/sap_table/header.rs
- src/webdynpro/element/complex/sap_table/mod.rs
- src/webdynpro/element/complex/sap_table/row.rs
- `SapTableBody` 및 `SapTableRow`에서 쉽게 값을 변환할 수 있도록 `FromSapTable` 트레이트를 추가했습니다.
- 기본 구현으로 `Vec<String>`, `Vec<(String, String)>` 을 구현했고, 이를 이용하도록 `CourseGrades` 내의 테이블 변환 과정을 리팩토링했습니다.
> [feat] `FromSapTable` 트레이트

- src/application/course_grades/mod.rs
- src/application/graduation_requirements/mod.rs
- src/application/graduation_requirements/model.rs
- src/application/mod.rs
- src/utils/de_with.rs
- src/webdynpro/element/complex/sap_table/body.rs
- src/webdynpro/element/complex/sap_table/row.rs
- src/webdynpro/element/mod.rs
- src/webdynpro/element/text/input_field.rs
- tests/application/graduation_requirements.rs
- tests/application/mod.rs
- `rowspan` 과 `colspan` 이 포함된 `SapTable` 에 대해 올바르게 `SapTableRow` 및 `SapTableBody` 가 생성되도록 수정했습니다.
- `InputField` 의 lsdata 구조 업데이트를 반영했습니다.
- `InputField` 의 value 값을 HTML Attribute 에서 바로 가져올 수 있는 메소드 `InputField::value()`를 추가했습니다.
- 엘리먼트의 LSData 파싱 실패 시 오류 메시지를 표준 입출력에 출력하도록 수정했습니다.
- 졸업에 필요한 학생 정보와 졸업 요건 및 졸업 가능 여부를 확인할 수 있는 `GraduationRequirements` 애플리케이션을 추가했습니다.
> [feat] `GraduationRequirements`(졸업사정표) 애플리케이션 구현

- .github/workflows/build_test.yml
- .github/workflows/publish.yml
- src/session/mod.rs
- `dev`, `main` 푸시 및 PR에 자동 테스트를 수행합니다.
- 매일 03시 23분에 자동 테스트를 수행합니다.
- 새로운 버전 릴리즈시 `crates.io` 에 배포합니다.
> [feat] 자동 테스트 & 배포를 위한 Actions

- Cargo.toml
- src/application/chapel/mod.rs
- src/application/course_grades/mod.rs
- src/application/course_grades/model.rs
- src/application/course_schedule/mod.rs
- src/application/graduation_requirements/mod.rs
- src/application/mod.rs
- src/webdynpro/command/element/mod.rs
- src/webdynpro/command/element/selection.rs
- src/webdynpro/command/element/text.rs
- 내부 애플리케이션 구현에서 명령 패턴을 더 사용하도록 리팩토링했습니다.
- getter를 코드에 작성하고 `getset` 의존성을 제거했습니다.
> [refactor] 명령 패턴 사용 및 불필요 의존성 제거

- src/application/graduation_requirements/mod.rs
- src/application/mod.rs
- src/application/student_information/model/academic_record.rs
- src/application/student_information/model/bank_account.rs
- src/application/student_information/model/family.rs
- src/application/student_information/model/mod.rs
- src/application/student_information/model/qualification.rs
- src/application/student_information/model/religion.rs
- src/application/student_information/model/research_bank_account.rs
- src/application/student_information/model/transfer.rs
- src/application/student_information/model/work.rs
- src/webdynpro/command/element/action.rs
- src/webdynpro/command/element/mod.rs
- src/webdynpro/command/element/selection.rs
- src/webdynpro/command/element/system.rs
- src/webdynpro/element/system/custom.rs
- `rusaint::application` 아래에 커맨드 패턴을 더 많은 곳에서 사용하도록 했습니다.
> [refactor] 커맨드 패턴 추가 사용

- .gitignore
- Cargo.toml
- rusaint-ffi/Cargo.toml
- rusaint-ffi/src/session.rs
- rusaint-ffi/uniffi.toml
- rusaint/Cargo.toml
- uniffi-bindgen/Cargo.toml
- uniffi-bindgen/uniffi-bindgen.rs
- `uniffi-bindgen` cli 툴을 통해 바인딩을 생성할 수 있도록 환경을 설정했습니다.
- `rusaint-ffi::session::USaintSessionBuilder`를 구현하여 세션을 생성할 수 있도록 했습니다.
> [feat] 바인딩 생성

- rusaint/src/application/graduation_requirements/mod.rs
- rusaint/src/application/student_information/mod.rs
- rusaint/tests/application/student_information.rs
- 애플리케이션이 하위 수준의 추상화 오류인 `WebDynproError` 대신 `RusaintError`를 반환하도록 수정했습니다.
> [refactor] 애플리케이션이 `WebDynproError` 대신 `RusaintError`를 반환하도록 변경

- rusaint-ffi/Cargo.toml
- rusaint-ffi/src/application/chapel.rs
- rusaint-ffi/src/application/course_grades.rs
- rusaint-ffi/src/application/course_schedule.rs
- rusaint-ffi/src/session.rs
- rusaint/Cargo.toml
- uniffi-bindgen/Cargo.toml
- `ffi` 환경에서 비동기 런타임이 정의되지 않은 문제를 해결
- `reqwest`에서 `openssl` 의존성을 제거하여 쉬운 빌드 환경 설정
> [refactor] `ffi` 오류 해결을 위한 코드 변경

- .github/workflows/release.yml
- languages/kotlin/lib/build.gradle.kts
- JReleaser 에서 레포지토리 버전 릴리즈 및 퍼블리싱이 정상적으로 진행되지 않는 문제 해결
- 버전 릴리즈에서 올바르게 바이너리, 바이트코드가 포함되지 않는 문제 해결
> [fix(kotlin)] JReleaser 릴리즈 오류 해결

- Cargo.toml
- packages/rusaint-ffi/Cargo.toml
- packages/rusaint/Cargo.toml
> [chore] 의존성 업데이트

- packages/rusaint/Cargo.toml
> [chore] `lol_html`을 2.1.0으로 업데이트

- .github/workflows/release-ios.yml
- 서브모듈을 삭제하고 메인 릴리즈가 완료된 후 릴리즈합니다.
- closes #160.
> [refactor(ios)] 서브모듈 삭제 및 릴리즈 방법 변경

- .github/workflows/build_test.yml
- .github/workflows/lint.yml
- .github/workflows/release-ios.yml
- Cargo.toml
- languages/kotlin/lib/build.gradle.kts
> release: 0.8.4-dev.0

- .coderabbit.yaml
- .github/workflows/build-test.yml
- .github/workflows/dry-run.yml
- .github/workflows/lint.yml
- `dev` 브랜치 삭제를 위해 `dev` 브랜치를 대상으로 한 워크플로를 `main` 대상으로 변경
> [chore] `dev` branch 삭제를 위한 워크플로 수정

- packages/rusaint/src/application/chapel/mod.rs
- packages/rusaint/src/application/course_grades/mod.rs
- packages/rusaint/src/application/course_schedule/mod.rs
- packages/rusaint/src/application/graduation_requirements/mod.rs
- packages/rusaint/src/application/lecture_assessment/mod.rs
- packages/rusaint/src/application/mod.rs
- packages/rusaint/src/application/personal_course_schedule/mod.rs
- packages/rusaint/src/application/student_information/mod.rs
- packages/rusaint/src/webdynpro/client/body/mod.rs
- packages/rusaint/src/webdynpro/client/mod.rs
- packages/rusaint/tests/application/chapel.rs
- packages/rusaint/tests/application/course_grades.rs
- packages/rusaint/tests/application/course_schedule.rs
- packages/rusaint/tests/application/graduation_requirements.rs
- packages/rusaint/tests/application/personal_course_schedule.rs
- packages/rusaint/tests/application/student_information.rs
- packages/rusaint/tests/tests.rs
- 안정성과 속도를 위해 애플리케이션을 재사용하여 테스트 수행
> [test] 애플리케이션 재사용

- .github/workflows/release-android.yml
- .github/workflows/release-ios.yml
- .github/workflows/release.yml
- LICENSE
- languages/kotlin/lib/build.gradle.kts
> [ci] Kotlin 릴리즈를 분리

- README.md
- packages/rusaint/src/webdynpro/element/layout/button_row.rs
> [docs] README 업데이트

- packages/rusaint/tests/webdynpro/element/button.rs
- packages/rusaint/tests/webdynpro/element/link.rs
- packages/rusaint/tests/webdynpro/element/mod.rs
> [test] Link element 테스트

- .github/workflows/release-android.yml
- .github/workflows/release-ios.yml
- .github/workflows/release-rn.yml
- react native 라이브러리 퍼블리싱 CI를 수정했습니다.
> ci: fix react native publishing

- README.md
- languages/react-native/README.md
- react-native 지원에 관한 README 추가
> [docs] react-native 관련 문서 추가

- .github/workflows/release-python.yml
- languages/python/pyproject.toml
- packages/rusaint-ffi/uniffi.toml
- 모듈 이름을 `rusaint`로 수정
- arm64 linux 환경에서 manylinux 빌드 문제 수정 (See https://github.com/briansmith/ring/issues/1728)
- 생성되는 cdylib 이름을 `rusaint_ffi`로 수정
> [fix] Python 배포 오류 수정

- .github/workflows/release-rn.yml
- languages/react-native/yarn.lock
- yarn.lock 최신화
- `--frozen-lockfile` 대신 `--immutable` flag를 사용하도록 수정
> [ci(rn)] 릴리즈 실패 오류 수정

- languages/react-native/package.json
> [fix(rn)] 잘못 작성된 bob 설정 수정

- packages/rusaint/src/session/mod.rs
- 토큰에서 WAF 쿠키가 존재하지 않아도 오류가 발생하지 않도록 수정하였습니다.
- (최근 사이트 변경에서 쿠키를 설정하지 않는 것으로 추정)
> [fix] 세션 생성 시 WAF 쿠키를 선택적으로 요구하도록 변경

- .github/workflows/release.yml
https://crates.io/docs/trusted-publishing
> [ci] trusted publishing 사용

- packages/rusaint/src/webdynpro/element/action/link.rs
- packages/rusaint/src/webdynpro/element/text/label.rs
- `Link`, `Label` element에서 text() 함수가 제대로 동작하지 않는 문제 수정
> [fix] `Link`, `Label`에 대한 Display 구현 수정

- .github/workflows/lint.yml
- packages/rusaint/Cargo.toml
- packages/rusaint/src/application/chapel/mod.rs
- packages/rusaint/src/application/course_grades/mod.rs
- packages/rusaint/src/application/course_schedule/mod.rs
- packages/rusaint/src/application/course_schedule/model.rs
- packages/rusaint/src/application/course_schedule/utils.rs
- packages/rusaint/src/application/graduation_requirements/mod.rs
- packages/rusaint/src/application/lecture_assessment/mod.rs
- packages/rusaint/src/application/mod.rs
- packages/rusaint/src/application/personal_course_schedule/mod.rs
- packages/rusaint/src/application/scholarships/mod.rs
- packages/rusaint/src/application/student_information/mod.rs
- packages/rusaint/src/session/mod.rs
- `wdpe@0.2.0`으로 마이그레이션합니다.
- ci lint가 모든 타겟과 피처를 검사하도록 수정합니다.
> [feat] `wdpe@0.2.0` 마이그레이션

- packages/rusaint/tests/application/course_schedule.rs
> [test] united_major 테스트 수정
