src/application/course_grades/mod.rs
src/application/course_grades/model.rs
src/application/mod.rs
src/utils.rs
tests/application/course_grades.rs

- `application::course_grades::CourseGrades` 를 `application::CourseGrades`로 Re-export하고 기존 모듈은 숨겼습니다.
- 성적 열람 관련 API의 명칭을 간단화했습니다.
- `grade_summary()` -> `semesters()`
- `grade_detail()` -> `classes()`
- 전체 합산 성적(학적부, 증명)을 열람하는 함수(`recorded_summary()`, `certificated_summary()`)를 추가하였습니다.
- 수업의 상세 성적만을 열람할 수 있는 함수 `class_detail()`을 추가했습니다.

[feat] CourseGrade API 완성

---

src/application/course_grades/mod.rs
src/application/course_schedule.rs
src/lib.rs
src/model/mod.rs
tests/application/course_grades.rs

- 학기를 데이터로 활용하는 함수를 실행할 때 이해하기 힘든 학기의 키 값(`090`, `091` 등) 대신 `SemesterType` enum을 이용하여 학기를 선택할 수 있도록 하였습니다.
- 일부 학기 관련 함수에서 `Period` 대신 `Semester` 용어를 사용하도록 수정하였습니다.

[refactor] SemesterType 추가

---

Cargo.toml
src/lib.rs
src/session/mod.rs
src/utils.rs

- WebDynpro 엔진 구현과 관련 없는 u-saint 관련 구현을 `model`과 `application` feature로 분리하였습니다.
- `application` feature는 `model` feature를 요구하며, 두 feature는 기본적으로 포함되므로 임의로 기본 feature를 제거하지 않는 이상 외부 변경사항은 없습니다.

[feat] u-saint 애플리케이션 구현을 feature 로 분리

---

src/lib.rs
tests/application/course_grades.rs
tests/tests.rs
tests/webdynpro/element/mod.rs

- `error::RusaintError`, `error::SsuSsoError`, `session::USaintSession`, `session::obtain_ssu_sso_token` 을 라이브러리 루트로 이동

[refactor] 오류와 세션 코드를 라이브러리 루트로 Re-export

---

src/application/course_grades/mod.rs
src/application/course_schedule.rs
src/application/mod.rs
src/webdynpro/application/mod.rs
src/webdynpro/element/action/mod.rs
src/webdynpro/element/complex/mod.rs
src/webdynpro/element/complex/sap_table/cell/mod.rs
src/webdynpro/element/complex/sap_table/mod.rs
src/webdynpro/element/graphic/mod.rs
src/webdynpro/element/layout/button_row.rs
src/webdynpro/element/layout/mod.rs
src/webdynpro/element/mod.rs
src/webdynpro/element/selection/list_box/item/action_item.rs
src/webdynpro/element/selection/list_box/item/mod.rs
src/webdynpro/element/selection/list_box/mod.rs
src/webdynpro/element/selection/mod.rs
src/webdynpro/element/system/mod.rs
src/webdynpro/element/text/mod.rs
tests/webdynpro/element/button.rs

- 엘리먼트를 가져올 때 더 짧은 경로를 가질 수 있도록 re-export 했습니다.
- 모듈 아래에 다수의 엘리먼트가 있는 경우 re-export 하지 않았고, 하위 엘리먼트가 있는 경우 최상위 엘리먼트는 re-export 하고 모듈 자체는 public 으로 유지하여 하위 엘리먼트에 접근할 수 있도록 했습니다.

[refactor] 엘리먼트 Re-export

---

src/application/course_grades/mod.rs
src/application/course_schedule.rs
src/webdynpro/element/complex/sap_table/body.rs
src/webdynpro/element/complex/sap_table/cell/mod.rs
src/webdynpro/element/complex/sap_table/mod.rs
src/webdynpro/element/complex/sap_table/property.rs
src/webdynpro/element/complex/sap_table/row.rs

- `SapTableBody` 를 자체 구조체로 변경하고 헤더 등 다양한 유틸리티 메소드 추가
- `SapTableRow` 구조체에 테이블 열에 담긴 추가 정보를 반영하고 셀 관련 유틸리티 메소드 추가

[refactor] `SapTable` 내용 파싱 개선

---

src/application/course_grades/mod.rs
src/webdynpro/element/mod.rs
src/webdynpro/element/selection/combo_box.rs
src/webdynpro/element/selection/list_box/mod.rs
src/webdynpro/element/system/client_inspector.rs
src/webdynpro/element/system/custom.rs
src/webdynpro/element/text/caption.rs
src/webdynpro/element/unknown.rs

- `Element::lsdata(&self)`의 리턴 타입을 `Option<&Self::ElementLSData>` 에서 `&Self::ElementLSData`로 변경

[refactor] 엘리먼트 LSData에 Option 제거

---

src/webdynpro/element/layout/button_row.rs
src/webdynpro/element/layout/tab_strip/mod.rs

- `&Vec`을 리턴하는 `ButtonRow::buttons()`, `TapStrip::tab_items()` 함수의 리턴 타입을 변경

[refactor] `&Vec`을 리턴하는 메소드를 Iterator를 리턴하도록 변경

---

src/application/course_grades/model.rs

- `getset`으로 자동 생성된 Getter 중 Copy가 가능한 타입은 get_copy로 생성되도록 하고, `String`의 경우 `&str`을 리턴하도록 직접 생성했습니다.

[refactor] Getter들이 API에서 일반적인 타입을 리턴하도록 변경

---

src/application/course_grades/mod.rs
src/application/course_schedule.rs
src/application/mod.rs
src/application/student_information.rs
src/error/mod.rs
src/lib.rs
src/webdynpro/client/mod.rs
src/webdynpro/command/element/action.rs
src/webdynpro/command/element/mod.rs
src/webdynpro/command/element/selection.rs
src/webdynpro/command/mod.rs
src/webdynpro/element/action/button.rs
src/webdynpro/element/complex/sap_table/mod.rs
src/webdynpro/element/complex/sap_table/property.rs
src/webdynpro/element/graphic/image.rs
src/webdynpro/element/layout/scrollbar.rs
src/webdynpro/element/layout/tray.rs
src/webdynpro/element/mod.rs
src/webdynpro/element/property/mod.rs
src/webdynpro/element/selection/combo_box.rs
src/webdynpro/element/selection/list_box/mod.rs
src/webdynpro/element/system/client_inspector.rs
src/webdynpro/element/system/custom.rs
src/webdynpro/element/unknown.rs
src/webdynpro/mod.rs
tests/application/course_grades.rs
tests/webdynpro/element/button.rs
tests/webdynpro/element/mod.rs

- `WebDynproCommand` 트레이트 구조체를 이용하여 `WebDynproClient`를 사용할 수 있도록 메소드를 추가했습니다.
- 일부 간단한 작업에 한해서 지원하며, `SapTable` 등의 복잡한 엘리먼트를 다룰 때에는 엘리먼트에 직접 접근하는 기존 방법을 사용하여야 합니다.
- 기존 형태의 `Application`을 제거하고 `WebDynproClient`(기존 `BasicWDApplication`)과 각 애플리케이션이 직접 상속되지 않도록 애플리케이션과 클라이언트를 완전히 분리하였습니다. 따라서 애플리케이션의 형태가 조금 더 유연해지고 구현하기 간단해집니다.
- 테이블 내용 등 복잡한 작업을 간단화할 방법 찾기

[feat] `WebDynproCommand` 객체를 이용한 클라이언트 제어

---

Cargo.toml
src/webdynpro/client/body/mod.rs
src/webdynpro/element/mod.rs

- `ElementDef::from_body` 를 사용할 때 해당 `ElementDef` 가 `ElementNodeId` 를 가지고 있다면 노드 ID 를 기반으로 탐색합니다(O(n) = 1)
- `ElementDef::with_node_id` 를 이용해 생성하여 이용할 수 있습니다.

[feat] `ElementDef`의 `NodeId` 기반 엘리먼트 탐색

---

src/application/course_grades/mod.rs
src/session/mod.rs
src/webdynpro/element/complex/sap_table/body.rs
src/webdynpro/element/complex/sap_table/cell/header_cell.rs
src/webdynpro/element/complex/sap_table/cell/hierarchical_cell.rs
src/webdynpro/element/complex/sap_table/cell/matrix_cell.rs
src/webdynpro/element/complex/sap_table/cell/mod.rs
src/webdynpro/element/complex/sap_table/cell/normal_cell.rs
src/webdynpro/element/complex/sap_table/cell/selection_cell.rs
src/webdynpro/element/definition/mod.rs
src/webdynpro/element/definition/sub.rs
src/webdynpro/element/layout/button_row.rs
src/webdynpro/element/mod.rs

- `impl Element`, `ElementWrapper`, `impl SubElement` 를 반환하는 함수들을  `ElementDef`, `ElementDefWrapper`, `SubElementDef`를 반환하도록 변경
- 추후 최적화 변경을 위해 `from_element_ref` 함수 추가

[refactor] `Element`반환 함수가 대신 `ElementDef`를 반환하도록 변경

---

src/application/chapel/mod.rs
src/application/chapel/model.rs
src/application/course_grades/model.rs
src/application/course_schedule/model.rs
src/application/graduation_requirements/model.rs
src/application/mod.rs
src/application/student_information/model/academic_record.rs
src/application/student_information/model/family.rs
src/application/student_information/model/transfer.rs
src/error/mod.rs
src/utils/de_with.rs
src/webdynpro/client/body/mod.rs
src/webdynpro/client/mod.rs
src/webdynpro/command/element/complex.rs
src/webdynpro/command/element/mod.rs
src/webdynpro/command/element/selection.rs
src/webdynpro/command/mod.rs
src/webdynpro/element/complex/sap_table/body.rs
src/webdynpro/element/complex/sap_table/from_sap_table.rs
src/webdynpro/element/complex/sap_table/header.rs
src/webdynpro/element/complex/sap_table/mod.rs
src/webdynpro/element/complex/sap_table/row.rs
tests/application/chapel.rs
tests/application/mod.rs

- `Chapel`(채플정보조회) 애플리케이션을 구현했습니다.
- `deserialize_f32_string`과 `deserialize_u32_string` 함수에서 trim 을 미리 수행하도록 하였습니다.
- 채플 정보가 없을 경우 `ApplicationError::NoChapelInformation` 을 반환합니다.
- 테이블 상의 빈 row를 읽어들이지 않도록 수정했습니다.
- 웹 요청을 수행하지 않는 명령을 위한 `WebDynproReadCommand` 트레이트를 추가했습니다.
- 기존 `Read~` 접두사를 가진 명령어가 `WebDynproReadCommand`를 구현하도록 했습니다.
- `SapTableBody`, `SapTableRow`와 `SapTableHeader`에 `ElementRef`를 제거하여 `'body` 라이프타임 의존성을 제거했습니다.
- `ReadSapTableBodyCommand` 명령을 추가했습니다.

[feat] `Chapel` 애플리케이션

---

src/application/chapel/mod.rs
src/application/chapel/model.rs
src/application/course_schedule/mod.rs
src/application/lecture_assessment/mod.rs
src/application/lecture_assessment/model.rs
src/application/mod.rs
src/application/personal_course_schedule/mod.rs
src/application/personal_course_schedule/model.rs
src/error/mod.rs
src/lib.rs
src/utils/de_with.rs
src/webdynpro/command/element/complex.rs
src/webdynpro/element/complex/sap_table/from_sap_table.rs
src/webdynpro/element/complex/sap_table/mod.rs
src/webdynpro/element/text/caption.rs
src/webdynpro/element/text/text_view.rs
tests/application/chapel.rs
tests/application/course_schedule.rs
tests/application/lecture_assessment.rs
tests/application/mod.rs
tests/application/personal_course_schedule.rs

- `PersonalCourseSchedule`(개인수업시간표) 애플리케이션을 구현했습니다.
- `LectureAssessment`(강의평가조회) 애플리케이션을 구현했습니다.
- `ApplicationError`를 pub 선언했습니다.
- `Chapel`, `PersonalCourseSchedule`, `CourseSchedule`에서 정보가 없을 때 올바른 오류를 반환하는지 확인하는 테스트 케이스를 추가했습니다.
- `TextView::text()`와 `Caption::text()`에서 개행이 표시되지 않는 문제를 수정했습니다.
- `SapTableVerticalScrollCommand`를 구현했습니다.

[feat] `PersonalCourseSchedule`, `LectureAssessment` 애플리케이션

---

src/application/chapel/mod.rs
src/application/course_grades/mod.rs
src/application/course_schedule/mod.rs
src/application/graduation_requirements/mod.rs
src/application/graduation_requirements/model.rs
src/application/lecture_assessment/mod.rs
src/application/mod.rs
src/application/personal_course_schedule/mod.rs
src/application/personal_course_schedule/model.rs
src/application/student_information/mod.rs
src/application/student_information/model/academic_record.rs
src/application/student_information/model/bank_account.rs
src/application/student_information/model/family.rs
src/application/student_information/model/graduation.rs
src/application/student_information/model/mod.rs
src/application/student_information/model/qualification.rs
src/application/student_information/model/religion.rs
src/application/student_information/model/research_bank_account.rs
src/application/student_information/model/transfer.rs
src/application/student_information/model/work.rs
tests/application/chapel.rs
tests/application/course_grades.rs
tests/application/course_schedule.rs
tests/application/graduation_requirements.rs
tests/application/lecture_assessment.rs
tests/application/personal_course_schedule.rs
tests/application/student_information.rs

- `impl USaintApplication` 인 모든 구조체에 `-Application` 접미사를 추가했습니다.
- 애플리케이션 명을 호출하는 경우는 적고, 애플리케이션들이 Application 접미사를 가지지 않음으로써 해당 애플리케이션에서 사용하는 모델들의 이름이 모호해지거나 지나치게 길어지는 문제를 해결하기 위함입니다.

[refactor] `impl USaintApplication` 구조체에 `-Application` 접두사 추가

---

rusaint/src/webdynpro/client/body/mod.rs
rusaint/src/webdynpro/client/mod.rs

- 모든 `Client` 내부 `Body`의 변경은 `EventQueue`를 통해 이루어지므로 `EventQueue`에 `Mutex`를 적용하여 동시에 여러 스레드가 웹 요청을 보낼 수 없도록 함

[refactor] 스레드 안전 `EventQueue`

---

rusaint/src/webdynpro/client/body/mod.rs
rusaint/src/webdynpro/client/mod.rs

- `scraper` 의존성 없이 `roxmltree`와 `regex_lite`만을 활용하여 `SapSsrClient`를 파싱합니다.
- #90 를 위해 직접 엘리먼트를 파싱하는 경우가 아니라면 HTML 파서를 제외해 라이브러리 경량화를 달성하기 위함입니다.

[refactor] `scraper` 없이 `SapSsrClient` 파싱

---

Cargo.toml
rusaint/Cargo.toml

- workspace 설정으로 바꾼 뒤, `crates.io` 에서 `README`가 표시되지 않는 문제 수정

[fix] `crates.io` 에서 `README`가 불러와지지 않는 문제 수정

---

.github/workflows/build_test.yml
.github/workflows/dry-run.yml

- `dry-run` 워크플로가 정상 작동하도록 수정
- `dry-run` 워크플로가 `build-test` 워크플로와 동시에 실행되지 않도록 `pull_request` 트리거 및 `concurrency` 설정 수정

[ci] `dry-run` 워크플로 수정

---

.github/workflows/release-ios.yml
.github/workflows/release.yml

- Actions runner 이미지의 `yq`를 `yq` 액션 대신 사용
- `macos-latest`에서는 yq 액션의 사용이 불가능

[ci] `yq`액션을 릴리즈에 사용하지 않도록 변경

---

.github/workflows/release-ios.yml
.github/workflows/release.yml

- `release`, `release-ios` 워크플로의 체크아웃 문제 해결
- `release-ios` 워크플로가 `rusaint-ios`의 릴리즈 정보를 확인하도록 변경

[ci] `release`, `release-ios` 워크플로의 체크아웃 문제 해결

---

.github/workflows/build-test.yml

- `build-test` 워크플로가 실행 중일 때 새로운 잡이 요청되었을 경우 기존 잡을 취소하지 않고 대기

[ci] 이미 빌드가 진행 중인 경우 취소하지 않고 대기

---

.coderabbit.yaml
.github/workflows/build-test.yml
.github/workflows/dry-run.yml
.github/workflows/lint.yml
.github/workflows/release-ios.yml
Cargo.toml
languages/kotlin/lib/build.gradle.kts

- 릴리즈 워크플로가 버전을 확인하게 되면서 브랜치 분리의 이유가 없어짐
- 정상적인 changelog 생성을 위해서도 dev 브랜치 삭제 필요

[chore] `dev` 브랜치 삭제

---

.github/workflows/build-test.yml
Cargo.toml
packages/rusaint-ffi/Cargo.toml
packages/rusaint/Cargo.toml
packages/rusaint/src/application/utils/input_field.rs
packages/rusaint/src/lib.rs
packages/rusaint/src/uniffi_support.rs
packages/rusaint/src/webdynpro/client/body/mod.rs
packages/rusaint/src/webdynpro/client/mod.rs
packages/rusaint/src/webdynpro/element/definition/mod.rs
packages/rusaint/src/webdynpro/element/macros.rs
packages/rusaint/src/webdynpro/element/selection/list_box/mod.rs
packages/rusaint/src/webdynpro/element/sub/definition.rs
packages/rusaint/tests/application/chapel.rs
packages/rusaint/tests/application/course_grades.rs
packages/rusaint/tests/application/course_schedule.rs
packages/rusaint/tests/application/graduation_requirements.rs
packages/rusaint/tests/application/lecture_assessment.rs
packages/rusaint/tests/application/personal_course_schedule.rs
packages/rusaint/tests/application/scholarships.rs
packages/rusaint/tests/application/student_information.rs
packages/rusaint/tests/tests.rs
packages/rusaint/tests/webdynpro/element/button.rs
packages/rusaint/tests/webdynpro/element/link.rs
packages/rusaint/tests/webdynpro/event/mod.rs
rust-toolchain.toml
uniffi-bindgen/Cargo.toml

- 로그 표시를 `log` crate로 하도록 변경했고, `pretty_env_logger`로 표시합니다.
- CI에서 테스트 시 `RUST_LOG=info`로 설정하여 로그를 더 자세히 표시합니다.

[refactor] 로깅 방법 변경 및 테스트 시 로그 표시 개선

---

README.md
packages/rusaint/src/application/course_grades/mod.rs
packages/rusaint/src/application/course_grades/model.rs
packages/rusaint/src/lib.rs

- SemesterGrade, ClassGrade의 year와 semester 타입을 각각 u32와 SemesterType으로 통일
- `avarage`오타를 `average`로 수정
전체적으로 검토하긴 했지만 SemesterGrade, ClassGrade 외에 year와 semester의 타입이 다른 모델이 또 있다면 알려주세요!

[fix] SemesterGrade, ClassGrade의 year와 semester 타입을 각각 `u32`와 `SemesterType`으로 통일

---

packages/rusaint/src/application/utils/de_with.rs

- SemesterType이 `CourseGradesApplication::semesters` 함수에서 역직렬화 되지 않는 문제 수정

[fix] SemesterType 역직렬화 오류 수정

---

packages/rusaint/src/application/utils/de_with.rs

- 채플, 성적 정보에서 학기 명이 `1 학기` -> `1학기` 로 변경되면서 발생한 역직렬화 오류 수정

[fix] `SemesterType` 역직렬화에 실패하는 문제 수정

---

packages/rusaint/src/webdynpro/element/action/link.rs
packages/rusaint/src/webdynpro/element/complex/sap_table/from_sap_table.rs
packages/rusaint/src/webdynpro/element/mod.rs
packages/rusaint/src/webdynpro/element/selection/check_box.rs
packages/rusaint/src/webdynpro/element/selection/combo_box.rs
packages/rusaint/src/webdynpro/element/text/caption.rs
packages/rusaint/src/webdynpro/element/text/input_field.rs
packages/rusaint/src/webdynpro/element/text/label.rs
packages/rusaint/src/webdynpro/element/text/text_view.rs

- 일반 string으로 표현될 수 있는 Element(`Link`, `Label`)에 대해 `Display` trait 을 구현합니다.
- `ElementWrapper::textise` 대신 `TryFrom<ElementWrapper> for String`을 구현하여 변환할 수 있도록 합니다.
고민: 가장 깔끔하게 하려면 모든 Element에 대해서 기본 Display trait을 구현하고 `ElementWrapper`에 대해 Display trait을 구현하는 것인데, 이렇게 되면
1. ElementWrapper가 각 element의 specialized display implementation을 통해 올바른 값이 표기되었는지 혹은 fallback method인 id 표시가 되었는지 caller 입장에서 알 수가 없음
2. Display가 T: ElementDefinition 에 대해 구현될 경우 [Autoref speicalization](https://github.com/dtolnay/case-studies/blob/master/autoref-specialization/README.md)을 통해 Display trait을 구현해야 하는데, 그렇게 되면 Display를 `T: ElementDefinition` 이 아닌 `&T: ElementDefinition` 에 대해 구현해야 하는 상황이 생김.
즉,
1. Element는 일반 Display 구현을 통해 Element 표기를 구현할 수 있어야 하고,
2. ElementWrapper에서는 Display 구현이 있는가 여부에 따라서 Ok/Err 를 반환할 …

[feat] `Link`, `Label`의 `Display` 구현 및 `textise` 리팩토링

---

packages/rusaint/src/application/graduation_requirements/model.rs

- `GraduationRequirement`의 필드/게터 오타 calcuation을 calculation으로 수정

[fix!] 오타난 필드명 수정 (calcuation->calculation)
